# Generated by Django 2.1.7 on 2019-04-11 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twitteruser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=140)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('twitter_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='twitteruser.TwitterUser')),
            ],
            options={
                'ordering': ('-time_stamp',),
            },
        ),
    ]
