# Generated by Django 2.1.7 on 2019-04-11 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='twitter_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitteruser.TwitterUser'),
        ),
    ]
